import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const DB_NAME = 'fitlens-local'
const STORE = 'meals'
const emptyMeal = { name: 'Awaiting analysis', calories: 0, protein: 0, carbs: 0, fat: 0, confidence: 0, fieldConfidence: {}, ingredients: [], portionBasis: '', assumptions: [], caveats: [], reasoning: '', createdAt: '' }

function openDb() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE, { keyPath: 'id', autoIncrement: true }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }) }
async function readMeals() { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE).objectStore(STORE).getAll(); request.onsuccess = () => resolve(request.result.reverse()); request.onerror = () => reject(request.error) }) }
async function saveMeal(meal) { const db = await openDb(); db.transaction(STORE, 'readwrite').objectStore(STORE).add(meal) }

async function preprocess(file) { const image = await createImageBitmap(file); const canvas = document.createElement('canvas'); canvas.width = 512; canvas.height = 512; canvas.getContext('2d').drawImage(image, 0, 0, 512, 512); return { dataUrl: canvas.toDataURL('image/jpeg', .82) } }

const schema = { type: 'object', additionalProperties: false, properties: { name: { type: 'string' }, ingredients: { type: 'array', items: { type: 'string' } }, portionBasis: { type: 'string' }, calories: { type: 'number' }, protein: { type: 'number' }, carbs: { type: 'number' }, fat: { type: 'number' }, confidence: { type: 'number' }, fieldConfidence: { type: 'object', additionalProperties: { type: 'number' } }, assumptions: { type: 'array', items: { type: 'string' } }, caveats: { type: 'array', items: { type: 'string' } }, reasoning: { type: 'string' } }, required: ['name', 'ingredients', 'portionBasis', 'calories', 'protein', 'carbs', 'fat', 'confidence', 'fieldConfidence', 'assumptions', 'caveats', 'reasoning'] }
const instruction = 'Analyze the food photo as a nutrition coach. Return only the requested JSON. Identify visible ingredients, explain the portion basis, list assumptions and uncertainty. Never present estimates as exact. confidence is 0-100 overall; fieldConfidence must include calories, protein, carbs, fat. Use one serving unless the image clearly indicates otherwise. Keep reasoning concise.'
function parseOutput(data) { const text = data.output?.flatMap(item => item.content || []).find(item => item.type === 'output_text')?.text || '{}'; return JSON.parse(text.replace(/```json|```/g, '').trim()) }

async function analyze(image) {
  const key = import.meta.env.VITE_OPENAI_API_KEY
  if (!key) return { ...emptyMeal, name: 'Sample chicken salad', ingredients: ['chicken breast', 'greens', 'tomato'], portionBasis: 'one visible plate', calories: 420, protein: 38, carbs: 24, fat: 18, confidence: 86, fieldConfidence: { calories: 82, protein: 89, carbs: 78, fat: 80 }, assumptions: ['Dressing is estimated as one tablespoon.', 'No hidden ingredients are included.'], caveats: ['Photo analysis cannot verify exact weight or recipe.'], reasoning: 'Visible chicken and vegetables suggest a lean, protein-forward meal.', demo: true }
  const body = { model: import.meta.env.VITE_OPENAI_MODEL || 'gpt-4.1-mini', input: [{ role: 'user', content: [{ type: 'input_text', text: instruction }, { type: 'input_image', image_url: image.dataUrl }] }], text: { format: { type: 'json_schema', name: 'food_analysis', strict: true, schema } } }
  const first = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify(body) })
  if (!first.ok) throw new Error('Vision analysis failed. Check your API key and model.')
  const result = parseOutput(await first.json())
  return result
}

function Confidence({ value = 0, label = 'Overall confidence' }) { return <span className="confidence"><span className="confidence-dot" /> {label} {Math.round(value)}%</span> }
function App() {
  const [meals, setMeals] = useState([]), [preview, setPreview] = useState(''), [loading, setLoading] = useState(false), [current, setCurrent] = useState(null), [error, setError] = useState('')
  useEffect(() => { readMeals().then(setMeals).catch(() => setError('Local storage is unavailable.')) }, [])
  const totals = meals.reduce((total, meal) => ({ calories: total.calories + (+meal.calories || 0), protein: total.protein + (+meal.protein || 0), carbs: total.carbs + (+meal.carbs || 0), fat: total.fat + (+meal.fat || 0) }), { calories: 0, protein: 0, carbs: 0, fat: 0 })
  async function onFile(event) { const file = event.target.files?.[0]; if (!file) return; setError(''); setLoading(true); try { const image = await preprocess(file); setPreview(image.dataUrl); const meal = { ...await analyze(image), createdAt: new Date().toISOString() }; await saveMeal(meal); setCurrent(meal); setMeals(await readMeals()) } catch (err) { setError(err.message || 'Analysis failed.') } finally { setLoading(false) } }
  return <div className="app"><header><div className="brand"><span className="brand-mark">✦</span><span>fitlens<span className="accent">.ai</span></span></div><div className="local"><span className="dot" /> local-only · IndexedDB</div></header>
    <main><section className="hero"><div className="hero-copy"><p className="eyebrow">PERSONAL NUTRITION COACH</p><h1>See your food<br /><em>with more clarity.</em></h1><p className="lead">A gentle photo-based coach that turns meals into useful, honest next steps.</p><div className="pill-row"><span>✦ Vision analysis</span><span>◌ Private by default</span></div></div><div className="upload glass"><div className="orb">{preview ? <img src={preview} alt="meal preview" /> : <span>◒</span>}</div><p>{loading ? 'Reading your meal...' : 'Share a meal to begin'}</p><label className="button">{loading ? 'Analyzing...' : 'Analyze photo'}<input type="file" accept="image/*" onChange={onFile} disabled={loading} /></label><small>Nothing leaves this device except the image sent to OpenAI when a key is configured.</small></div></section>
      {error && <div className="error">{error}</div>}{current && <section className="result glass"><div className="result-top"><div><p className="eyebrow">LATEST INSIGHT</p><h2>{current.name}</h2><Confidence value={current.confidence} /></div><div className="score">{Math.round(current.confidence)}<small>%</small><span>confidence</span></div></div><div className="macro-grid">{[['Calories', current.calories, 'kcal'], ['Protein', current.protein, 'g'], ['Carbs', current.carbs, 'g'], ['Fat', current.fat, 'g']].map(([label, value, unit]) => <div className="macro" key={label}><span>{label}</span><strong>{value}<small>{unit}</small></strong><i><b style={{ width: `${current.fieldConfidence?.[label.toLowerCase()] || current.confidence}%` }} /></i><em>{current.fieldConfidence?.[label.toLowerCase()] || current.confidence}%</em></div>)}</div><div className="notes"><div><b>Assumptions & care</b>{(current.assumptions || []).concat(current.caveats || []).slice(0, 3).map((note, i) => <p key={i}>• {note}</p>)}</div><div><b>Why this estimate</b><p>{current.reasoning || 'Based on visible ingredients and estimated serving size.'}</p><p className="portion">Portion basis: {current.portionBasis}</p></div></div><div className="ingredients"><b>Visible ingredients</b>{(current.ingredients || []).map(item => <span key={item}>{item}</span>)}</div></section>}
      <section className="dashboard"><div className="section-head"><div><p className="eyebrow">TODAY · JUL 15</p><h2>Your dashboard</h2></div><span className="muted">Goal 2,000 kcal</span></div><div className="stats"><div className="calorie glass"><span>Calories consumed</span><strong>{totals.calories.toLocaleString()} <small>/ 2,000 kcal</small></strong><div className="bar"><i style={{ width: `${Math.min(100, totals.calories / 20)}%` }} /></div></div>{[['Protein', 'protein', 'g'], ['Carbs', 'carbs', 'g'], ['Fat', 'fat', 'g']].map(([label, key, unit]) => <div className="stat glass" key={key}><span>{label}</span><strong>{totals[key]}<small>{unit}</small></strong><b>{key === 'protein' ? 'On a good track' : 'Keep logging'}</b></div>)}</div></section>
      <section className="history"><div className="section-head"><div><p className="eyebrow">MEAL LOG</p><h2>Recent meals</h2></div><span className="muted">{meals.length} meals</span></div>{meals.length === 0 ? <div className="empty glass">Your first meal will appear here.</div> : <div className="meal-list glass">{meals.slice(0, 5).map((meal, index) => <article className="meal" key={index}><div className="meal-icon">{index % 2 ? '◌' : '✦'}</div><div className="meal-info"><strong>{meal.name}</strong><span>{new Date(meal.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · <Confidence value={meal.confidence} label="" /></span></div><div className="meal-kcal"><strong>{meal.calories}</strong><span>kcal</span></div></article>)}</div>}</section>
    </main><footer><span>fitlens.ai</span><span>Your data stays on your device.</span></footer></div>
}
createRoot(document.getElementById('root')).render(<App />)
